module --force purge
module load Stages/2025
module load GCC/13.3.0
module load ParaStationMPI
module load NCCL
module load MPI-settings/CUDA
module load UCX-settings/RC-CUDA
module load Python
module load CuPy
module load FFTW
module load mpi4py
module load SciPy-Stack
