stages:
  - benchmark
  - upload

benchmark-base:
  image: mambaorg/micromamba
  stage: benchmark
  artifacts:
    paths:
      - output.json

  before_script:
    - micromamba create --yes -f etc/environment-base.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
  script:
    - pytest --continue-on-collection-errors -v pySDC/tests -m "benchmark" --benchmark-json output.json


upload_results:
  stage: upload

  before_script:
    - apt-get update -y && apt-get install openssh-client -y
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
#    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PUSH_KEY_GITHUB" | tr -d '\r' | DISPLAY=":0.0" setsid ssh-add - > /dev/null
  script:
    - git clone git@github.com:Parallel-in-Time/pySDC-benchmarks.git



