stages:
  - lint
  - test
  - benchmark
  - upload

lint:
  image: mambaorg/micromamba
  stage: lint
  before_script:
    - micromamba create --yes -f etc/environment-lint.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
  script:
    - black pySDC  --check --diff --color
    - flakeheaven lint --benchmark pySDC

test-base:
  image: mambaorg/micromamba
  stage: test
  variables:
    NAME: 'base'
  parallel:
    matrix:
      - PYTHON: [ '3.7', '3.8', '3.9', '3.10' ]
  artifacts:
    paths:
      - coverage_$NAME_$PYTHON.dat
  before_script:
    - micromamba create --yes python=$PYTHON -f etc/environment-$NAME.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
  script:
    - coverage run --data-file=coverage_$NAME_$PYTHON.dat -m pytest --continue-on-collection-errors -v --durations=0 pySDC/tests -m "not fenics and not petsc and not mpi4py and not benchmark"

test-libs:
  image: mambaorg/micromamba
  stage: test
  parallel:
    matrix:
      - PYTHON: [ '3.7', '3.8', '3.9', '3.10' ]
        NAME: ['fenics', 'petsc', 'mpi4py']
  artifacts:
    paths:
      - coverage_$NAME_$PYTHON.dat
  before_script:
    - micromamba create --yes python=$PYTHON -f etc/environment-$NAME.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
    - micromamba install --yes -c conda-forge openssh
  script:
    - coverage run --data-file=coverage_$NAME_$PYTHON.dat -m pytest --continue-on-collection-errors -svv --durations=0 pySDC/tests -m $NAME

benchmark-base:
  image: mambaorg/micromamba
  stage: benchmark
  artifacts:
    paths:
      - output.json

  before_script:
    - micromamba create --yes -f etc/environment-base.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
  script:
    - pytest --continue-on-collection-errors -v pySDC/tests -m "benchmark" --benchmark-json output.json


merge_coverage:
  image: mambaorg/micromamba
  stage: benchmark
  variables:
    COV_TOKEN: ${COV_TOKEN}
  artifacts:
#    paths:
#      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  before_script:
    - micromamba create --yes -f etc/environment-base.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
    - micromamba install -c conda-forge git
#    - git config --global --add safe.directory '*'
  script:
    - python -m coverage combine coverage_*.dat
    - python -m coverage xml
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_JOB_URL
    - echo $CI_COMMIT_REF_NAME
#    - export COVERALLS_REPO_TOKEN=$COV_TOKEN
#    - export CI_NAME=gitlab
#    - export CI_BUILD_NUMBER=$CI_COMMIT_SHORT_SHA
#    - export CI_BUILD_URL=$CI_JOB_URL
#    - export CI_BRANCH=$CI_COMMIT_REF_NAME
#    - coveralls

upload_results:
  image: ubuntu:latest
  stage: upload
  variables:
    KEY: ${SSH_PUSH_KEY_GITHUB}

  before_script:
    - apt-get update -y && apt-get install openssh-client git -y
    - eval $(ssh-agent -s)
    - echo "$KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "sig.pancetta+github@gmail.com"
    - git config --global user.name "pancetta"
  script:
    - git clone git@github.com:Parallel-in-Time/pySDC-benchmarks.git
    - cd pySDC-benchmarks
    - mkdir -p latest-benchmark
    - cd latest-benchmark
    - cp ../../*.json .
#    - cd ..
#    - mkdir -p latest-coverage
#    - cd latest-coverage
#    - cp ../../coverage.xml .
    - cd ..
    - git add -A
    - git commit -m "adding new benchmark results"
    - git push
