stages:
  - lint
  - test
  - benchmark
  - upload

lint:
  image: mambaorg/micromamba
  stage: lint
  before_script:
    - micromamba create --yes -f etc/environment-lint.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
  script:
    - black pySDC  --check --diff --color
    - flakeheaven lint --benchmark pySDC

test-base:
  image: mambaorg/micromamba
  stage: test
  variables:
    NAME: 'base'
  parallel:
    matrix:
      - PYTHON: [ '3.7', '3.8', '3.9', '3.10' ]
  artifacts:
    paths:
      - coverage_$NAME_$PYTHON.dat
  before_script:
    - micromamba create --yes python=$PYTHON -f etc/environment-$NAME.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
  script:
    - coverage run --data-file=coverage_$NAME_$PYTHON.dat -m pytest --continue-on-collection-errors -v --durations=0 pySDC/tests -m "not fenics and not petsc and not mpi4py and not benchmark"

test-libs:
  image: mambaorg/micromamba
  stage: test
  parallel:
    matrix:
      - PYTHON: [ '3.7', '3.8', '3.9', '3.10' ]
        NAME: ['fenics', 'petsc', 'mpi4py']
  artifacts:
    paths:
      - coverage_$NAME_$PYTHON.dat
  before_script:
    - micromamba create --yes python=$PYTHON -f etc/environment-$NAME.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
    - sudo apt-get install ssh
  script:
    - coverage run --data-file=coverage_$NAME_$PYTHON.dat -m pytest --continue-on-collection-errors -svv --durations=0 pySDC/tests -m $NAME

benchmark-base:
  image: mambaorg/micromamba
  stage: benchmark
  artifacts:
    paths:
      - output.json

  before_script:
    - micromamba create --yes -f etc/environment-base.yml
    - eval "$(micromamba shell hook --shell=bash)"
    - micromamba activate pySDC
  script:
    - pytest --continue-on-collection-errors -v pySDC/tests -m "benchmark" --benchmark-json output.json


upload_results:
  image: ubuntu:latest
  stage: upload
  variables:
    KEY: ${SSH_PUSH_KEY_GITHUB}

  before_script:
    - apt-get update -y && apt-get install openssh-client git -y
    - eval $(ssh-agent -s)
    - echo "$KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "sig.pancetta+github@gmail.com"
    - git config --global user.name "pancetta"
  script:
    - git clone git@github.com:Parallel-in-Time/pySDC-benchmarks.git
    - cd pySDC-benchmarks
    - mkdir -p latest-benchmark
    - cd latest-benchmark
    - cp ../../*.json .
    - mkdir -p latest-coverage
    - cd latest-coverage
    - cp ../../coverage_*.dat .
    - git add -A
    - git commit -m "adding new benchmark and coverage results"
    - git push
