---

name: pySDC
channels:
  - conda-forge
  - defaults
dependencies:
  - mpi4py>=3.0.0
  - mpi4py-fft>=2.0.2
  - mpich
  - matplotlib>=3.0
  - dill>=0.2.6
  - scipy>=0.17.1
  - pip
  - pip:
    - qmat>=0.1.8
