name: pySDC
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.18,<=1.21
  - scipy>=0.17.1
  - matplotlib>=3.0
  - sympy>=1.0
  - numba>=0.35
  - dill>=0.2.6
  - pytest
  - pytest-benchmark
  - coverage[toml]
  - sphinx
  - coveralls