---

name: pySDC
channels:
  - conda-forge
dependencies:
  - coverage[toml]
  - sphinx
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  - myst-nb
  - jupytext
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - dill
  - numba
  - cupy
  - pip
  - pip:
    - sphinxemoji
    - m2r2
    - genbadge[all]
    - qmat>=0.1.8
