---

name: pySDC
channels:
  - conda-forge
dependencies:
  - numpy>=1.15.4
  - scipy>=0.17.1
  - matplotlib>=3.0
  - dill>=0.2.6
  - fenics>=2019.1.0
  - mpi4py<=3.1.4
  - pip
  - pip:
    - qmat>=0.1.8
