name: pySDC_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.15.4
  - scipy>=0.17.1
  - matplotlib>=3.0,<=3.5.3
  - dill>=0.2.6
  - mpich
  - mpi4py>=3.0.0
  - pytest
  - pytest-cov
  - jupyter
  - ipyparallel
  - pip
  - ipython
