name: CI pipeline for pySDC users

on:
  push:

jobs:

  user_cpu_tests:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'Parallel-in-Time'}}

    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
        env: ['base', 'fenics', 'mpi4py', 'petsc']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main

        with:
          environment-file: "etc/environment-${{ matrix.env }}.yml"

        extra-specs: |
            python=${{ matrix.python }}

      - name: Run pytest for CPU stuff
        run: |
          pytest -v --durations=0 pySDC/tests -m ${{ matrix.env }}
